Feature
VladislavYurich/spa-webbee pull request #1
Opened 2024-07-08 12:36 UTC by VladislavYurich

![image](https://github.com/VladislavYurich/spa-webbee/assets/123568543/0b952916-f5ce-4d46-a1a8-9edb10463868)
![image](https://github.com/VladislavYurich/spa-webbee/assets/123568543/ce797570-d158-4ae4-804d-963f7ef6236c)
![image](https://github.com/VladislavYurich/spa-webbee/assets/123568543/a72df32d-6773-4bef-ae53-9c852bac93f5)

2024-07-08 15:38 UTC, heyanniemoran requested changes

2024-07-08 15:38 UTC, heyanniemoran commented on index.html
> +                    </a>
Нужно без onClick

2024-07-08 15:38 UTC, heyanniemoran commented on js/map.js
> +
Пустые строки надо убрать

2024-07-08 15:38 UTC, heyanniemoran commented on js/timer.js
setInterval накапливает ошибку, нужен другой подход.

2024-07-08 15:38 UTC, heyanniemoran commented on timer.html
> +                </button>
В идеале alt именовать как то, что внутри содержится, т.е. chevron / update / close

2024-07-09 07:15 UTC, Mary-fox commented on home.html
> +                            <img src="./img/Calendar.svg" alt="Scheme">
я бы сюда добавила семантики

2024-07-09 07:15 UTC, Mary-fox commented on js/map.js
> +        var myMap = new ymaps.Map("map", {
а где используется map.js? Увидела только newMap

2024-07-09 07:15 UTC, Mary-fox commented on timer.html
> +                </button>
class=""  а зачем?

2024-07-09 07:21 UTC, Mary-fox commented on index.html
> +                <div class="header__top--right">
нужно реализовать переход назад на главную

2024-07-16 07:31 UTC, heyanniemoran commented
![image](https://github.com/user-attachments/assets/926f6ffe-5536-40f6-b6aa-80d4fac646c8)

https://vladislavyurich.github.io/spa-webbee/

2024-07-16 09:12 UTC, VladislavYurich commented
Правки внесены

2024-07-16 09:56 UTC, heyanniemoran commented
Поплыла верстка
![image](https://github.com/user-attachments/assets/1349bfe3-dd06-4387-a148-f04d15614895)

2024-07-16 09:57 UTC, heyanniemoran commented
Не открывается нормально, если я открываю, например, сразу таймер 
![image](https://github.com/user-attachments/assets/27a91efa-1451-471d-b4e6-c413386d6080)

2024-07-17 13:04 UTC, Mary-fox commented
если нажимаем на стрелочку назад, то таймер слетает

2024-07-17 13:06 UTC, Mary-fox approved these changes

2024-07-17 13:07 UTC, heyanniemoran approved these changes

2024-07-17 13:18 UTC, merged